### ISSUE TITLE
Compilation fails on Swift 5.5 [known issue until Xcode ships with macOS 12 SDK]

### ISSUE THREAD

**Issue by pokryfka** [apple/swift-distributed-tracing-baggage#16]
### Environment:

```
swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
Target: x86_64-apple-macosx11.0
```

### Steps:

```
swift build
```

### Result:

```
/xxx/swift-distributed-tracing-baggage/Sources/InstrumentationBaggage/Baggage.swift:232:5: error: unknown attribute 'TaskLocal'
    @TaskLocal public static var current: Baggage?
    ^
[2/2] Compiling InstrumentationBaggage BaggageKey.swift
```

### Expected result:

Additional steps/requirements like extra compilation flags described in `README.md` and, if possible, included in the manifest file `Package.swift`.

**Comment by ktoso** [comment]
I'm assuming you got that Swift from the Xcode 12 RC -- it is known to not be working as it includes the "old" macOS 11 SDK which does not have concurrency in it. Long story short: there will be a new Xcode with the macOS 12 SDK at some point, ad that point it things will actually work as they should.

More information here: https://github.com/swift-server/swift-service-lifecycle/issues/110#issuecomment-921356359

**Comment by pokryfka** [comment]
Its Swift 5.5 shipped with Xcode 13 installed via App Store.

Thank you for the link and explanation, much appreciated and helpful.

I dont want to install another Xcode which is super heavy but will try installing another Swift version and test compilation on Linux via Docker.

Looking forward to the Xcode with the macOS 12 SDK!

**Comment by pokryfka** [comment]
> Long story short: This is an issue with Xcode and the SDK it ships. It couldn't ship macOS 12 SDK since macOS 12 isn't "released" yet. There will be a new Xcode with the macOS 12 SDK at some point, ad that point it things will actually work as they should.

> More information here: [swift-server/swift-service-lifecycle#110 (comment)](https://github.com/swift-server/swift-service-lifecycle/issues/110#issuecomment-921356359)

With that said, I am not sure why is it related to macOS SDK.
As far as I understand `@TaskLocal` is a Swift feature and should work on iOS as well.

I do use `AsyncHTTPClient` and `Soto` in some iOS projects.
As of now Soto does not depend on `swift-distributed-tracing-baggage` but as far as I know its planned,
in order to be able to use future releases of Soto on iOS `swift-distributed-tracing-baggage` has to compile on iOS SDK.

**Comment by ktoso** [comment]
Right that's (sadly) expected expected with that Xcode then. Too bad with the timing this year but that's how it ended up as.

Thanks for checking in! We're also looking forward to the Xcode with the newest SDK :)

**Comment by pokryfka** [comment]
I think this one can be closed, the package builds without problems using Xcode 13.1

**Comment by ktoso** [comment]
Thanks for the ping! Yep that's right.

Now we have the same adventures kind of with 5.6 needing projects 😆  😭  but thankfully not this one.
