### ISSUE TITLE
`Baggage.$current.withValue` vs `Baggage.withValue` and actors

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-distributed-tracing-baggage#36]
If I call either `Baggage.$current.withValue` or `Baggage.withValue` from an actor where the closure accesses the same actor I get different results. The first compiles fine and the second errors with the following
```
non-sendable type '() async throws -> ()' exiting actor-isolated context in call to non-isolated static method 'withValue(_:operation:)' cannot cross actor boundary
```

**Comment by ktoso** [comment]
Thanks for reporting this was fixed in https://github.com/apple/swift-distributed-tracing-baggage/commit/b7aeba8b534d2b4ddd2edcbcb791d99b98e4dd43
